name: .NET Core CI/CD

on:
  push:
    branches:
      - master  # Trigger the pipeline when pushing to the 'master' branch.
  pull_request:
    branches:
      - master  # Trigger on pull requests targeting the 'master' branch.
  workflow_dispatch:  # This allows you to trigger the workflow manually

jobs:
  build:
    runs-on: ubuntu-latest  # This sets the environment to use an Ubuntu runner.

    steps:
    - name: Checkout code
      uses: actions/checkout@v2  # This step checks out the code from your GitHub repository.

    - name: Set up .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '5.0'  # Specify the .NET version you're using. Change if needed.

    - name: Restore dependencies
      run: dotnet restore  # Restores project dependencies.

    - name: Build the project
      run: dotnet build --configuration Release  # Builds the project in Release mode.

    - name: Run tests
      run: dotnet test --configuration Release --no-build --verbosity normal  # Runs tests.

    - name: Publish the app
      run: dotnet publish --configuration Release --output ./publish  # Publishes the app.
