name: .NET Core CI/CD

on:
  push:
    branches:
      - master  # Trigger the pipeline when pushing to the 'master' branch.
  pull_request:
    branches:
      - master  # Trigger on pull requests targeting the 'master' branch.

jobs:
  build:
    runs-on: ubuntu-latest  # This sets the environment to use an Ubuntu runner.

    steps:
    - name: Checkout code
      uses: actions/checkout@v2  # This step checks out the code from your GitHub repository.

    - name: Install libssl3
      run: sudo apt-get update && sudo apt-get install -y libssl3  # Install libssl3 for .NET 8 compatibility.

    - name: Set up .NET 8
      uses: actions/setup-dotnet@v2  # This is for .NET Core 8.
      with:
        dotnet-version: '8.0'  # Specify the .NET 8 version you're using.

    - name: Restore dependencies
      run: dotnet restore  # Restores project dependencies.

    - name: Build the project
      run: dotnet build --configuration Release  # Builds the project in Release mode.

    - name: Run tests
      run: dotnet test --configuration Release --no-build --verbosity normal  # Runs tests.

    - name: Publish the app
      run: dotnet publish --configuration Release --output ./publish  # Publishes the app.
